# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: M2YzN2VmNmVmZDYzNDVjODk3ZmI2YmJmMDc1N2M3ODMzZmExYTJhMmU0MjhlMmI4ZjkzYzVhOTZhNjA2YWE2MGIzNTY5OTRlOGM1MGQwOTdmZjE5YmFjYjQ1ZDFjZGVlZGFlNzAyM2YzMzIzNGU1MTY5ZjczY2JlZGUwMzEwZGQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
